topo_name: topo08
mgmt_network: stuttgart
mgmt_subnet: 99.1.8.0/24
node_image: alpine:latest # use harbor.nice.nokia.net/docker/alpine:latest if needed
nodes:
  - name: r1
    mgmt_ipv4: 99.1.8.11
  - name: r2
    mgmt_ipv4: 99.1.8.12
  - name: r3
    mgmt_ipv4: 99.1.8.13
  - name: r4
    mgmt_ipv4: 99.1.8.14
links:
  - a: r1:eth1
    b: r2:eth1
  - a: r2:eth1
    b: r3:eth1
  - a: r3:eth1
    b: r4:eth1
  - a: r4:eth1
    b: r1:eth1
